### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by JoanComasFdz** [pocki/jupyter-dotnet#1]
Would it be possible to update the Dockerfile so that it uses .NET6 SDK?

**Comment by pocki** [comment]
Sorry, had not much time. 

I have now updated to .NET 6 SDK with latest stable Dotnet.interactive, samples and the latest jupyter base images.

Docker images are pushed with tag 20220210 and latest.

**Comment by JoanComasFdz** [comment]
That was fast, thanks a lot!
